### PR TITLE
Add `-V` and `--version` to argparse to easily get HATCHet version.

### PR DESCRIPTION
**Pull request by aholmes**
This change follows a community standard for displaying the version already stored in `__init__.py` as `__version__` when users use the `-V` or `--version` switches.

### CODE REVIEW

**Comment by vineetbansal** [comment]
Thanks @aholmes .. `hatchet` has recently undergone (with v0.3.0) some changes in its commands (old commands are still supported though) that make this PR not directly mergeable. The top-level `hatchet` command does list the version number now, but we see what you're getting at here: a `-V` or `--version` flag for all supported `hatchet` commands will be helpful to view and parse programmatically if need be. Let me incorporate these changes today.

**Comment by aholmes** [comment]
> Thanks @aholmes .. `hatchet` has recently undergone (with v0.3.0) some changes in its commands (old commands are still supported though) that make this PR not directly mergeable. The top-level `hatchet` command does list the version number now, but we see what you're getting at here: a `-V` or `--version` flag for all supported `hatchet` commands will be helpful to view and parse programmatically if need be. Let me incorporate these changes today.

Great, thanks for that info. I'm happy to make that change for this PR if it makes your life easier.

**Comment by vineetbansal** [comment]
Hi @aholmes .. as you can tell from this PR now, we've taken your idea and incorporated it into the several places where it would have made sense (all the commands supported by `HATCHet`). So I'm going to close this PR - thanks for making `HATCHet` better!

**Comment by aholmes** [comment]
> Hi @aholmes .. as you can tell from this PR now, we've taken your idea and incorporated it into the several places where it would have made sense (all the commands supported by `HATCHet`). So I'm going to close this PR - thanks for making `HATCHet` better!

Great, glad it's in there. In the future, I am happy to participate with your team to get these changes up-to-date and mergable.

**Pull request closed without merging**
